version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - exhaustive
    - godot
    - goheader
    - gomodguard
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - staticcheck
    - unconvert
    - unused
    - whitespace
formatters:
  enable:
    - gofmt
    - goimports
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
      no-inline-comments: true
      no-prefix-comments: true
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'
