dist: trusty
sudo: required
services:
- docker
language: go
go:
  - "1.11.x"
env:
  - GOFLAGS=-mod=vendor GO111MODULE=on

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh

script:
- make test
- make vet

branches:
  only:
  - master
  - /v\d+\.\d+\.\d+/
matrix:
  fast_finish: true
  allow_failures:
  - go: tip

before_deploy:
  - GOOS=linux go build -o terraform-provider-ccloud_${TRAVIS_TAG}_linux
  - GOOS=darwin go build -o terraform-provider-ccloud_${TRAVIS_TAG}_darwin
  - GOOS=windows go build -o terraform-provider-ccloud_${TRAVIS_TAG}_windows.exe

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: IZkxFmfphY9Iqp9mZQ6GOBzPNaEahzFL6Jh2v3tcXqQWZimOI3rSbLlz948UI0ZVEmYcp7j4QsuCWJF1YpSvYR+SKq+E1TyAoGvBWC51qgzFowHSNPcDnMzUs2NGjKyWuQgK9waAgQqwT3Hgwvs5+y87eSHe5d55oYH9w7fiZfXMEEIzOxGW/VIYEEXqD/vrSEsEr/2uu2aWyrPSr43Rf3bYfGTTme54MEBl9IA7WacdrMvOQVo4c4CT4ktBylY3reWcN/f9vmb7MvY8RLKvpWeSEPlAORSXZv7TaHO9luQsBRHXdA7+qqMnYS6LU+B/61VREyAD+R8J/OY4HkzbVOLOWiNmWXIaJFU28b2XXyj6pgmfNlRa3r8uj3Cr2ZNN6QkYtiCExThuvlKQgSGfEGhG2gTIqQB0KnL6NG6i4PKsxmYSadxKb/r+Vpz3VV7NlKgFByKs6Vm/83DekRQpt0uZTBPW09QBP0TxZtmipaRh7Oh1SxUICszj1Vcm0S4D+zWWAJntb70eA0t6nLrtLuXjabFkIgC/xmhPoTqbC/6961DPRm8Pyquux4rqsfvPHZVtXLwy5AmEnjGF7vL47VsmvKazAYjAOK9KjA7PMYii2vkcPQMhzxCJLghPxtMyy0VBiJVCVN4z6Ap+cAUwcpx/uEXfgtmcMXL4JdV9ipw=
  file_glob: true
  file:
  - terraform-provider-ccloud_${TRAVIS_TAG}_*
  on:
    repo: sapcc/terraform-provider-ccloud
    tags: true
    all_branches: true
